import Head from 'next/head';
import Header from '../components/Header'
import Banner from '../components/Banner'
import HomeBooks from '../components/HomeBooks';

export default function Index() {
 

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Header></Header>
     <Banner></Banner>
     <HomeBooks></HomeBooks> 
    </>
  )
}
