import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Picture from '../../public/Picture.svg';
import Logo from '../../public/Logo.svg';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Index() {
  const [isNameInputVisible, setIsNameInputVisible] = useState(false);

  const handleRegisterClick = () => {
    setIsNameInputVisible((prevValue) => !prevValue);
  };

  return (
    <>
      <Head>
        <title>Piton Technology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div>
          <Image src={Picture} alt="Landscape picture" width={720} height={1024} />
        </div>
        <div>
          <div className="mt-20 ml-72">
            <Image src={Logo} alt="Logo picture" width={120} height={78} />
          </div>
          <div>
            <p className={styles.welcomeText}>Welcome back!</p>
            <h2 className={styles.titleLogin}>Login to your account</h2>
          </div>
          <div className="flex">
            <div>
              <div>
                {isNameInputVisible && (
                  <div className="ml-40 mt-10">
                    <label className="block text-xl" htmlFor="">
                      Name
                    </label>
                    <input
                      className="border rounded-sm w-96 h-14 whitetone border-none mt-2 p-2"
                      placeholder="John Doe"
                      type="name"
                      required
                    />
                  </div>
                )}
                <div className="ml-40 mt-10">
                  <label className="block text-xl" htmlFor="">
                    E-mail
                  </label>
                  <input
                    className="border rounded-sm w-96 h-14 whitetone border-none mt-2 p-2"
                    placeholder="john@mail.com"
                    type="email"
                    required
                  />
                </div>
                <div className="ml-40 mt-10">
                  <label className="block text-xl" htmlFor="">
                    Password
                  </label>
                  <input
                    className="block border rounded-sm w-96 h-14 whitetone border-none mt-2 p-2 placeholder:text-6xl"
                    placeholder="........"
                    type="password"
                    required
                  />
                  <div className="flex items-center">
                    <input
                      className="mt-3 w-5 h-5 ring-3 ring-purple-600 text-purple-600 bg-purple-700 rounded border-purple-600 focus:ring-purple-600  focus:ring-4"
                      type="checkbox"
                      name=""
                      id="default-checkbox"
                    />
                    <label className="ml-3 mt-3 purple text-xl" htmlFor="default-checkbox">
                      Remember Me
                    </label>
                  </div>
                </div>
                <div>
                  <Link href='/home'>
                  <div
                    className="flex flex-row justify-center items-center mt-20 ml-40 p-2 gap-2 w-96 h-16 absolute bg-red-500 rounded-md text-white text-2xl"
                    style={{ background: '#EF6B4A' }}>
                    Login
                  </div>
                  </Link>
                  <div className="flex flex-row justify-center items-center mt-40 ml-40 p-2 gap-2 w-96 h-16 absolute bg-white rounded-md purple border border-purple-500 text-2xl" 
                  onClick={() => handleRegisterClick(!isNameInputVisible)}>
                  Register
                </div>
            </div>
          </div>
        </div>
      </div>
           </div>
          <div>
          </div>
        </div>
    </>
  )
}
